### ISSUE TITLE
Error: getaddrinfo ENOTFOUND

### ISSUE THREAD

**Issue by pavini** [banzeh/cielo#1]
Ola,
Primeiro, obrigado pelo pacote! :)

Estou tentando usar, com base nos exemplos que passou e estou recebendo o seguinte erro:

ERRO { Error: getaddrinfo ENOTFOUND apisandbox.cieloecommerce.cielo.com.br apisandbox.cieloecommerce.cielo.com.br:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'apisandbox.cieloecommerce.cielo.com.br',
  host: 'apisandbox.cieloecommerce.cielo.com.br',
  port: 443 }

Algo que eu possa estar fazendo errado?

**Comment by banzeh** [comment]
@pavini, boa tarde.

Qual função você está tentando chamar?

Aparentemente o seu dns não está retornando o ip do servidor da Cielo. Tente pingar o endereço e veja se retorna o IP da Cielo (104.41.42.101).

Abraços.
