### ISSUE TITLE
Sem retorno no ambiente de testes

### ISSUE THREAD

**Issue by pavini** [banzeh/cielo#10]
Ola banzeh,

Quando seto o sandbox: true, eu não recebo nada de retorno. Sem erro, sem Json.
Se coloco true no sandbox, eu recebo autorização negada por conta de usar um numero de cartão inválido.

Estou usando o 
node v10.0.0
npm v5.6.0

**Comment by banzeh** [comment]
@pavini na sandbox não tem retorno de nada e em produção ele dá erro por cartão inválido? É isso?

**Comment by pavini** [comment]
Flavio, obrigado pelo rápido retorno.

É isso mesmo. No ambiente de produção recebe a mensagem de transação não aprovada, e quando mudo para testes, ele simplesmente não retorna nada.

Lendo uma outra inssue aqui, eu usei as chaves que indicou para testes e passou a funcionar.

Att.
Pavini

**Comment by banzeh** [comment]
No issue #8 eu percebi que a conexão com a Cielo era encerrada e o pacote acabava não retornando nem erro e nem sucesso. Isso foi corrigido na versão 1.0.4.
