### ISSUE TITLE
Adicionando opção para cancelar recorrencia agenda.

### ISSUE THREAD

**Issue by renanmoraes** [banzeh/cielo#13]
**Is your feature request related to a problem? Please describe.**
```
curl
curl --request PUT "https://apisandbox.cieloecommerce.cielo.com.br/1/RecurrentPayment/{RecurrentPaymentId}/Deactivate"
--header "Content-Type: application/json"
--header "MerchantId: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
--header "MerchantKey: 0123456789012345678901234567890123456789"
--header "RequestId: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
--data-binary
--verbose
```

[URL CIELO](https://developercielo.github.io/manual/cielo-ecommerce#desabilitando-um-pedido-recorrente)

**Describe the solution you'd like**
Desabilitar um pedido recorrente

**Additional context**
Seria muito importante ter a parte de cancelamento do pagamento recorrente junto a cielo.

**Comment by banzeh** [comment]
@renanmoraes bom dia.

O pacote foi atualizado para a versão 1.0.8.

Nessa versão é possível fazer as modificações nas recorrências, incluindo o cancelamento da recorrência.

#### <a name="modifyRecurrenceDeactivate"></a> Desabilitando um Pedido Recorrente

```js
const updateDeactivate = {
  "recurrentPaymentId": RecurrentPaymentId
}

cielo.recurrentPayments.modify.Deactivate(updateDeactivate)
  .then((data) => {
    return console.log(data);
  })
  .catch((err) => {
    return console.error('ERRO', err);
  })
```

Ou usando await

```js
const deactivate = await cielo.recurrentPayments.modify.Deactivate(updateDeactivate)
```
