### ISSUE TITLE
Ocorre um erro ao fazer a requisição. StatusCode: 400.

### ISSUE THREAD

**Issue by luandro** [banzeh/cielo#19]
Por muito tempo funcionava tudo corretamente. Mas recentemente comecei a receber esse erro da Cielo:

`Ocorre um erro ao fazer a requisição. StatusCode: 400.`

Estou usando chaves de acesso ao sandbox recém geradas. Alguma ideia do que pode ser?

**Comment by banzeh** [comment]
@luandro , boa tarde.

Qual a chamada que vc está utilizando?

**Comment by Cauen** [comment]
Pra quem também sofreu com esse problema, no meu caso foi porque eu enviei a bandeira como "Mastercard" e o correto seria "MASTERCARD" ou EnumBrands.MASTER
