### ISSUE TITLE
Code 101

### ISSUE THREAD

**Issue by jmourace** [banzeh/cielo#2]
Olá, recebo o codigo 101 - MerchantId is required.
Passo os parâmetros usando como referencia sua descrição e com MerchantId cadastrado na Cielo.
Pode me ajudar com esse erro?
Obrigado

**Comment by banzeh** [comment]
Bom dia.

Atualizei o código com a opção de debug nos parâmetros para verificar os dados que estão sendo enviados para a Cielo.

Pode atualizar o pacote, ativar o debug e colar aqui o resultado para eu verificar? (Não esqueça de substituir as chaves por xxxx).

**Comment by jmourace** [comment]
Bom dia Flavio, obrigado por responder.
O erro era meu.
Mas vou atualizar o código.
Obrigado.

Enviado do Email<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

________________________________
De: Flavio Takeuchi <notifications@github.com>
Enviado: Thursday, November 16, 2017 11:01:19 AM
Para: banzeh/cielo
Cc: JOAO CARLOS MOURA; Author
Assunto: Re: [banzeh/cielo] Code 101 (#2)


Bom dia.

Atualizei o código com a opção de debug nos parâmetros para verificar os dados que estão sendo enviados para a Cielo.

Pode atualizar o pacote, ativar o debug e colar aqui o resultado para eu verificar? (Não esqueça de substituir as chaves por xxxx).
