### ISSUE TITLE
Tratamento dos dados para boleto

### ISSUE THREAD

**Issue by odirleiborgert** [banzeh/cielo#20]
Olá,

É mais uma dúvida do que feature.... mas senão tiver isso seria legal implementar... os dados que envio para geração de boleto, como um endereço com acentuação, a lib "banzeh/cielo" já faz todo o tratamento desses dados?

**Comment by banzeh** [comment]
Bom dia.

Não existe nenhum tratamento, mas é uma ótima ideia, já que acentuação acaba causando erro também em casos de cartão de crédito também.

**Comment by odirleiborgert** [comment]
para boletos eu sei que enfrentei diversos problemas.... qualquer caractere especial, ponto, espaço duplo....  sei que tiver que dar um trim em todos os campos...

isso é o que lembro

**Comment by odirleiborgert** [comment]
Existe essa biblioteca que talvez pode ajudar, ser dependência?
https://www.npmjs.com/package/normalize-strings

**Comment by banzeh** [comment]
@odirleiborgert foi implementado já um tratamento para caracteres especiais, só esqueci de avisar 🤦‍♂️

Obrigado pela contribuição. 

Abraços.
