### ISSUE TITLE
Tratamento de Dados pagamento Cartão.

### ISSUE THREAD

**Issue by troyamtec** [banzeh/cielo#25]
Gostaria que fosse implementado a utilização de casas decimais na API. Estou com meu cadastro fechado na Cielo e eu não faço ideia do motivo pelos quais eles fecharam o meu cadastro. O que eu posso imaginar é que seja pela utilização de casas decimais na hora de tentar efetuar o pagamento. 
Não faço ideia do motivo do bloqueio e acredito também que falta alertar à equipe de segurança que existem programadores que utilizam a API e por um simples valor TRUE/FALSE ou até mesmo casas decimais podem resultar em problemas e que os tais não podem ser considerados como tentativa de fraude.
Eu passei horas implementando a API de vocês e infelizmente eu agora estou com o meu cadastro bloqueado e estão pedindo um prazo de 180 dias para "estudar o caso".

Peço por gentileza que seja feita algo em relação à isso. Estou com meu aplicativo parado por conta disso.
Atenciosamente,
Marcos Porto

**Comment by banzeh** [comment]
@troyamtec boa tarde.

Esse **pacote não é oficial da Cielo**. Como tive que desenvolver para um projeto, disponibilizei o código no Github e no NPM para outras pessoas que tivessem a mesma necessidade.

Em relação às casas decimais, na utilização do webservice 3.0 da Cielo não são aceitas, devendo ser **enviado o valor em centavos**. Isso é uma característica do serviço da Cielo.

Para mais informações, consulte a documentação oficial em https://developercielo.github.io/manual/cielo-ecommerce.

Se tiver alguma dúvida na utilização do pacote, pode postar aqui mesmo que farei o que puder para te auxiliar.

Abraços.
