### ISSUE TITLE
Busca dos cartões registrados

### ISSUE THREAD

**Issue by ezequielvictor** [banzeh/cielo#27]
Olá, 

Fiz algumas modificações locais apenas para fazer o GET com o cartão tokenizado e gostaria de saber se você poderia fazer estas alterações também para futuros projetos que possam utilizar e para nós também.

O método no cielo.js ficou assim: 

```
controller.consultaTokenizedCard = (data) => {
  const o = {
    hostname: URL_CONSULTA,
    path: `/1/card/${data.token}`,
    method: 'GET'
  }
  
  return get(Object.assign(requestOptions, o), data)
}
```

No index.js em 'cards'

 ```
cards: {
      createTokenizedCard: cielo.createTokenizedCard,
      consultaTokenizedCard: cielo.consultaTokenizedCard
    },
```

E para a documentação 

```
const cartao= {
    "token": '66b2c162-efbf-4692-aee5-e536c0f81037'
}

const card = await cielo.cards.consultaTokenizedCard(cartao)

console.log('Consulta token', card)
```

ou

```
cielo.cards.consultaTokenizedCard(cartao)
.then((data) => {
    console.log(data)
})
.catch((err) => {
    console.log(err);
})
```

Obrigado.

**Comment by banzeh** [comment]
Oi @ezequielvictor , bom dia.

Show de bola cara, vou tentar dar uma olhada nisso no final de semana.

Se quiser, você pode clonar o repositório e enviar um pull request com o código alterado. Dessa forma, você vai aparecer na aba de [colaboradores](https://github.com/banzeh/cielo/graphs/contributors) aqui do github, o que acha? :)

**Comment by ezequielvictor** [comment]
Bom dia @banzeh vou fazer, desculpe a demora!
