### ISSUE TITLE
Consulta bin 

### ISSUE THREAD

**Issue by ezequielvictor** [banzeh/cielo#28]
Gostaria de saber se para reconhecer a bandeira do cartão vc utiliza uma API diferente da ConsultaBin para mandar o Request de uma compra.
Pois estou testando aqui, o ConsultaBin funciona apenas com cartões Visa e Master, fora isso, não está reconhecendo certo de acordo com os 6 números que passo como parâmetro.

**Comment by dexfs** [comment]
Se você estiver usando o sandbox talvez esteja ativo só pra essas bandeiras, de acordo com a documentação da cielo esse recurso é habilitado pelo suporte da cielo, o lojista tem que entrar em contato pra isso. 

https://developercielo.github.io/manual/cielo-ecommerce#consulta-bin
