### ISSUE TITLE
Consulta de Vendas

### ISSUE THREAD

**Issue by rzorzal** [banzeh/cielo#3]
Acredito que o URL para consulta de transações esteja errado (apisandbox.cieloecommerce.cielo.com.br).
Pela documentação deveria buscar de "https://apiquerysandbox.cieloecommerce.cielo.com.br".

Usei as URL's de sandbox para ilustrar o problema.
Acredito que basta alterar o URL para que a consulta funcione.
Vou submeter uma PR assim que terminar de editar localmente.

**Comment by banzeh** [comment]
Obrigado pela contribuição, vou adicionar mais alguns teste e irei atualizar o NPM.

Obrigado.

**Comment by banzeh** [comment]
Atualizado.

Obrigado pela ajuda @rzorzal

**Comment by rzorzal** [comment]
Vi aqui a atualização. Aproveitei e atualizei meu projeto tb. Obrigado pelo pacote ;)
