### ISSUE TITLE
Uso com TS

### ISSUE THREAD

**Issue by yanestevesufjf** [banzeh/cielo#37]
Estou tentando utilizar junto com o firebase cloud functions utilizando typescript (v3.2.2) e cielo (^1.1.2) mas não consigo importar o módulo. Diz que não existe, já alterei tsconfig.json para aceitar JS e nada.

Alguém sabe como posso importar o módulo e usar perfeitamente no ts ou devo portar o código do módulo pra typescript para conseguir a importação?

**Comment by banzeh** [comment]
Boa noite @yanestevesufjf , não utilizei o pacote ainda com Typescript, então não sei te responder. Acredito que deveria funcionar da mesma forma, já que ts também aceita Javascript.

Vou fazer um teste aqui. Já comecei a migrar o pacote para TS, mas por falta de tempo ainda não consegui produzir uma versão nova.

**Comment by banzeh** [comment]
@yanestevesufjf foi disponibilizada nova versão no npm com suporte ao typescript totalmente tipado.
