### ISSUE TITLE
Merchant Key

### ISSUE THREAD

**Issue by matheusgs05** [banzeh/cielo#6]
Realizei várias formas de cadastro no site da Cielo, porém em nenhum lugar consigo encontrar a Merchant Key necessária para a API.
Como faço para obter a chave e começar a testar?

**Comment by rzorzal** [comment]
Tente se cadastrar por [aqui](https://cadastrosandbox.cieloecommerce.cielo.com.br/), ao final irá gerar suas chaves para o sandbox da cielo.

**Comment by banzeh** [comment]
@matheusgs05 bom dia.

Conseguiu obter a Merchant Key?

Caso não tenha conseguido, sugiro que entre em contato direto com a Cielo para mais informações.

Email: cieloeCommerce@cielo.com.br
Capitais: 4002-9700
Demais Cidades: 0800 570 1700
Horário de atendimento: 24h por dia, 7 dias por semana.
